const chartOfAccounts = {
  nepal: {
    name: 'Nepal',
    currency: 'NPR',
    currencySymbol: 'रू',
    vatRate: 13,
    fiscalYearStart: '2082-04-01',
    taxYear: 'Mid-July to Mid-July (BS)',
    defaultDateFormat: 'bs',
    tdsRates: {
      'salary': 1, 'contract': 1.5, 'consulting': 1.5,
      'rent': 5, 'interest': 5, 'commission': 1.5, 'dividend': 5,
    },
    accounts: [
      { code: '10100', name: 'Cash (Nagad)', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '10200', name: 'Bank Account', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '10300', name: 'Accounts Receivable (Debi)', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '10350', name: 'EMI Receivable', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '10360', name: 'Bank EMI Loan Settlement (Clearing)', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '10370', name: 'EMI Customer A/C (Debtor)', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '10351', name: 'Advance TDS / TDS Receivable', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '10400', name: 'Inventory Stock', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '10450', name: 'Used / Exchange Goods Stock', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '10501', name: 'VAT Input (13%)', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '10502', name: 'VAT Credit Carry-Forward', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '10600', name: 'Prepaid Expenses', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '11100', name: 'Furniture & Fixtures', type: 'asset', category: 'fixed_asset', isSystem: true },
      { code: '11200', name: 'Office Equipment', type: 'asset', category: 'fixed_asset', isSystem: true },
      { code: '11300', name: 'Vehicles', type: 'asset', category: 'fixed_asset', isSystem: true },
      { code: '11400', name: 'Accumulated Depreciation', type: 'asset', category: 'contra_asset', isSystem: true },
      { code: '20100', name: 'Accounts Payable (Credi)', type: 'liability', category: 'current_liability', isSystem: true },
      { code: '20200', name: 'VAT Output (13%)', type: 'liability', category: 'current_liability', isSystem: true },
      { code: '20300', name: 'TDS Payable', type: 'liability', category: 'current_liability', isSystem: true },
      { code: '20320', name: 'TDS Payable - Service', type: 'liability', category: 'current_liability', isSystem: true },
      { code: '20330', name: 'TDS Payable - Contract/Goods', type: 'liability', category: 'current_liability', isSystem: true },
      { code: '20400', name: 'Accrued Expenses', type: 'liability', category: 'current_liability', isSystem: true },
      { code: '20500', name: 'Short-term Loans', type: 'liability', category: 'current_liability', isSystem: true },
      { code: '21100', name: 'Bank Loans', type: 'liability', category: 'long_term_liability', isSystem: true },
      { code: '30100', name: "Owner's Capital", type: 'equity', category: 'equity', isSystem: true },
      { code: '30200', name: 'Drawings', type: 'equity', category: 'equity', isSystem: true },
      { code: '30300', name: 'Retained Earnings', type: 'equity', category: 'equity', isSystem: true },
      { code: '30400', name: 'Profit & Loss (Current Year)', type: 'equity', category: 'equity', isSystem: true },
      { code: '40100', name: 'Sales Revenue (Bikri)', type: 'revenue', category: 'revenue', isSystem: true },
      { code: '40200', name: 'Sales Discount/Return', type: 'revenue', category: 'contra_revenue', isSystem: true },
      { code: '40300', name: 'Interest Income', type: 'revenue', category: 'other_income', isSystem: true },
      { code: '40400', name: 'VAT Exempt Sales', type: 'revenue', category: 'revenue', isSystem: true },
      { code: '50100', name: 'Cost of Goods Sold', type: 'expense', category: 'cogs', isSystem: true },
      { code: '50101', name: 'Purchase (Khareed)', type: 'expense', category: 'cogs', isSystem: true },
      { code: '50102', name: 'Purchase Return', type: 'expense', category: 'cogs', isSystem: true },
      { code: '50103', name: 'Transport & Customs', type: 'expense', category: 'cogs', isSystem: true },
      { code: '60100', name: 'Salary & Wages', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60200', name: 'Rent', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60300', name: 'Electricity & Utilities', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60400', name: 'Telephone & Internet', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60500', name: 'Office Supplies', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60510', name: 'Stationery', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60600', name: 'Marketing & Advertising', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60610', name: 'Sales Commission', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60700', name: 'Repair & Maintenance', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60710', name: 'Insurance', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60720', name: 'Communication', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60800', name: 'Depreciation', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60900', name: 'Bank Charges & Fees', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '61000', name: 'TDS Expenses', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '61010', name: 'Bad Debts', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '61100', name: 'Miscellaneous Expenses', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '61200', name: 'Professional Fees', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '61300', name: 'Contract / Service Charges', type: 'expense', category: 'operating_expense', isSystem: true },
    ],
  },

  india: {
    name: 'India',
    currency: 'INR',
    currencySymbol: '₹',
    vatRate: 18,
    fiscalYearStart: '2025-04-01',
    taxYear: 'April to March',
    defaultDateFormat: 'ad',
    gstRates: [0, 5, 12, 18, 28],
    tdsRates: {
      'salary': 10, 'contract': 10, 'consulting': 10,
      'rent': 10, 'interest': 10, 'commission': 5, 'dividend': 10,
    },
    accounts: [
      { code: '10100', name: 'Cash in Hand', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '10200', name: 'Bank Account', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '10300', name: 'Sundry Debtors', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '10400', name: 'Inventory', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '10501', name: 'Input GST (CGST)', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '10502', name: 'Input GST (SGST)', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '10503', name: 'Input IGST', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '10600', name: 'Prepaid Expenses', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '11100', name: 'Furniture & Fixtures', type: 'asset', category: 'fixed_asset', isSystem: true },
      { code: '11200', name: 'Plant & Machinery', type: 'asset', category: 'fixed_asset', isSystem: true },
      { code: '11300', name: 'Vehicles', type: 'asset', category: 'fixed_asset', isSystem: true },
      { code: '11400', name: 'Accumulated Depreciation', type: 'asset', category: 'contra_asset', isSystem: true },
      { code: '20100', name: 'Sundry Creditors', type: 'liability', category: 'current_liability', isSystem: true },
      { code: '20201', name: 'Output GST (CGST)', type: 'liability', category: 'current_liability', isSystem: true },
      { code: '20202', name: 'Output GST (SGST)', type: 'liability', category: 'current_liability', isSystem: true },
      { code: '20203', name: 'Output IGST', type: 'liability', category: 'current_liability', isSystem: true },
      { code: '20300', name: 'TDS Payable', type: 'liability', category: 'current_liability', isSystem: true },
      { code: '20400', name: 'PF Payable', type: 'liability', category: 'current_liability', isSystem: true },
      { code: '20500', name: 'ESI Payable', type: 'liability', category: 'current_liability', isSystem: true },
      { code: '21100', name: 'Term Loans', type: 'liability', category: 'long_term_liability', isSystem: true },
      { code: '30100', name: 'Capital Account', type: 'equity', category: 'equity', isSystem: true },
      { code: '30200', name: 'Drawings', type: 'equity', category: 'equity', isSystem: true },
      { code: '30300', name: 'Reserves & Surplus', type: 'equity', category: 'equity', isSystem: true },
      { code: '30400', name: 'Profit & Loss A/c', type: 'equity', category: 'equity', isSystem: true },
      { code: '40100', name: 'Sales', type: 'revenue', category: 'revenue', isSystem: true },
      { code: '40200', name: 'Sales Returns', type: 'revenue', category: 'contra_revenue', isSystem: true },
      { code: '40300', name: 'Other Income', type: 'revenue', category: 'other_income', isSystem: true },
      { code: '50100', name: 'Cost of Goods Sold', type: 'expense', category: 'cogs', isSystem: true },
      { code: '50101', name: 'Purchases', type: 'expense', category: 'cogs', isSystem: true },
      { code: '50102', name: 'Purchase Returns', type: 'expense', category: 'cogs', isSystem: true },
      { code: '50103', name: 'Freight & Duties', type: 'expense', category: 'cogs', isSystem: true },
      { code: '60100', name: 'Salaries', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60200', name: 'Rent', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60300', name: 'Electricity', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60400', name: 'Telephone & Internet', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60500', name: 'Office Expenses', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60600', name: 'Advertising', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60700', name: 'Repairs & Maintenance', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60800', name: 'Depreciation', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60900', name: 'Bank Charges', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '61000', name: 'Professional Fees', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '61100', name: 'Miscellaneous Expenses', type: 'expense', category: 'operating_expense', isSystem: true },
    ],
  },

  usa: {
    name: 'United States',
    currency: 'USD',
    currencySymbol: '$',
    vatRate: 0,
    salesTaxRate: 7.5,
    fiscalYearStart: '2025-01-01',
    taxYear: 'January to December',
    defaultDateFormat: 'ad',
    tdsRates: {},
    accounts: [
      { code: '10100', name: 'Cash', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '10200', name: 'Checking Account', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '10300', name: 'Accounts Receivable', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '10400', name: 'Inventory', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '10500', name: 'Prepaid Expenses', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '11100', name: 'Office Equipment', type: 'asset', category: 'fixed_asset', isSystem: true },
      { code: '11200', name: 'Vehicles', type: 'asset', category: 'fixed_asset', isSystem: true },
      { code: '11300', name: 'Accumulated Depreciation', type: 'asset', category: 'contra_asset', isSystem: true },
      { code: '20100', name: 'Accounts Payable', type: 'liability', category: 'current_liability', isSystem: true },
      { code: '20200', name: 'Sales Tax Payable', type: 'liability', category: 'current_liability', isSystem: true },
      { code: '20300', name: 'Payroll Liabilities', type: 'liability', category: 'current_liability', isSystem: true },
      { code: '20400', name: 'Income Tax Payable', type: 'liability', category: 'current_liability', isSystem: true },
      { code: '21100', name: 'Long-term Debt', type: 'liability', category: 'long_term_liability', isSystem: true },
      { code: '30100', name: "Owner's Equity", type: 'equity', category: 'equity', isSystem: true },
      { code: '30200', name: "Owner's Draw", type: 'equity', category: 'equity', isSystem: true },
      { code: '30300', name: 'Retained Earnings', type: 'equity', category: 'equity', isSystem: true },
      { code: '40100', name: 'Sales Revenue', type: 'revenue', category: 'revenue', isSystem: true },
      { code: '40200', name: 'Sales Returns & Allowances', type: 'revenue', category: 'contra_revenue', isSystem: true },
      { code: '40300', name: 'Other Income', type: 'revenue', category: 'other_income', isSystem: true },
      { code: '50100', name: 'Cost of Goods Sold', type: 'expense', category: 'cogs', isSystem: true },
      { code: '50200', name: 'Purchases', type: 'expense', category: 'cogs', isSystem: true },
      { code: '60100', name: 'Salaries & Wages', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60200', name: 'Rent Expense', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60300', name: 'Utilities', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60400', name: 'Office Supplies', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60500', name: 'Advertising', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60600', name: 'Insurance', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60700', name: 'Depreciation Expense', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60800', name: 'Professional Fees', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60900', name: 'Bank Charges', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '61000', name: 'Miscellaneous Expense', type: 'expense', category: 'operating_expense', isSystem: true },
    ],
  },

  uk: {
    name: 'United Kingdom',
    currency: 'GBP',
    currencySymbol: '£',
    vatRate: 20,
    fiscalYearStart: '2025-04-06',
    taxYear: 'April 6 to April 5',
    defaultDateFormat: 'ad',
    tdsRates: {},
    accounts: [
      { code: '10100', name: 'Cash', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '10200', name: 'Bank', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '10300', name: 'Debtors', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '10400', name: 'Stock', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '10501', name: 'VAT Input', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '10600', name: 'Prepayments', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '11100', name: 'Office Equipment', type: 'asset', category: 'fixed_asset', isSystem: true },
      { code: '11200', name: 'Vehicles', type: 'asset', category: 'fixed_asset', isSystem: true },
      { code: '11300', name: 'Accumulated Depreciation', type: 'asset', category: 'contra_asset', isSystem: true },
      { code: '20100', name: 'Creditors', type: 'liability', category: 'current_liability', isSystem: true },
      { code: '20201', name: 'VAT Output', type: 'liability', category: 'current_liability', isSystem: true },
      { code: '20300', name: 'PAYE Payable', type: 'liability', category: 'current_liability', isSystem: true },
      { code: '20400', name: 'National Insurance', type: 'liability', category: 'current_liability', isSystem: true },
      { code: '21100', name: 'Loans', type: 'liability', category: 'long_term_liability', isSystem: true },
      { code: '30100', name: 'Capital', type: 'equity', category: 'equity', isSystem: true },
      { code: '30200', name: 'Drawings', type: 'equity', category: 'equity', isSystem: true },
      { code: '30300', name: 'Retained Earnings', type: 'equity', category: 'equity', isSystem: true },
      { code: '40100', name: 'Turnover', type: 'revenue', category: 'revenue', isSystem: true },
      { code: '40200', name: 'Sales Returns', type: 'revenue', category: 'contra_revenue', isSystem: true },
      { code: '40300', name: 'Other Income', type: 'revenue', category: 'other_income', isSystem: true },
      { code: '50100', name: 'Cost of Sales', type: 'expense', category: 'cogs', isSystem: true },
      { code: '50200', name: 'Purchases', type: 'expense', category: 'cogs', isSystem: true },
      { code: '60100', name: 'Wages & Salaries', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60200', name: 'Rent', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60300', name: 'Utilities', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60400', name: 'Telephone & Internet', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60500', name: 'Office Expenses', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60600', name: 'Advertising', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60700', name: 'Repairs & Maintenance', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60800', name: 'Depreciation', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60900', name: 'Bank Charges', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '61000', name: 'Accountancy Fees', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '61100', name: 'Sundry Expenses', type: 'expense', category: 'operating_expense', isSystem: true },
    ],
  },

  australia: {
    name: 'Australia',
    currency: 'AUD',
    currencySymbol: 'A$',
    vatRate: 10,
    fiscalYearStart: '2025-07-01',
    taxYear: 'July 1 to June 30',
    defaultDateFormat: 'ad',
    tdsRates: {},
    accounts: [
      { code: '10100', name: 'Cash', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '10200', name: 'Business Bank Account', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '10300', name: 'Trade Debtors', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '10400', name: 'Stock on Hand', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '10501', name: 'GST Paid (Input)', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '10600', name: 'Prepayments', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '11100', name: 'Office Equipment', type: 'asset', category: 'fixed_asset', isSystem: true },
      { code: '11200', name: 'Motor Vehicles', type: 'asset', category: 'fixed_asset', isSystem: true },
      { code: '11300', name: 'Accumulated Depreciation', type: 'asset', category: 'contra_asset', isSystem: true },
      { code: '20100', name: 'Trade Creditors', type: 'liability', category: 'current_liability', isSystem: true },
      { code: '20201', name: 'GST Collected (Output)', type: 'liability', category: 'current_liability', isSystem: true },
      { code: '20300', name: 'PAYG Withholding', type: 'liability', category: 'current_liability', isSystem: true },
      { code: '20400', name: 'Superannuation Payable', type: 'liability', category: 'current_liability', isSystem: true },
      { code: '21100', name: 'Loans', type: 'liability', category: 'long_term_liability', isSystem: true },
      { code: '30100', name: 'Capital', type: 'equity', category: 'equity', isSystem: true },
      { code: '30200', name: 'Drawings', type: 'equity', category: 'equity', isSystem: true },
      { code: '30300', name: 'Retained Earnings', type: 'equity', category: 'equity', isSystem: true },
      { code: '40100', name: 'Sales', type: 'revenue', category: 'revenue', isSystem: true },
      { code: '40200', name: 'Sales Returns', type: 'revenue', category: 'contra_revenue', isSystem: true },
      { code: '40300', name: 'Other Income', type: 'revenue', category: 'other_income', isSystem: true },
      { code: '50100', name: 'Cost of Goods Sold', type: 'expense', category: 'cogs', isSystem: true },
      { code: '50200', name: 'Purchases', type: 'expense', category: 'cogs', isSystem: true },
      { code: '60100', name: 'Staff Wages', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60200', name: 'Rent', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60300', name: 'Electricity', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60400', name: 'Telephone & Internet', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60500', name: 'Office Expenses', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60600', name: 'Advertising', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60700', name: 'Repairs', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60800', name: 'Depreciation', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60900', name: 'Bank Fees', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '61000', name: 'Accounting Fees', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '61100', name: 'Miscellaneous', type: 'expense', category: 'operating_expense', isSystem: true },
    ],
  },

  canada: {
    name: 'Canada',
    currency: 'CAD',
    currencySymbol: 'C$',
    vatRate: 5,
    fiscalYearStart: '2025-01-01',
    taxYear: 'January to December',
    defaultDateFormat: 'ad',
    tdsRates: {},
    accounts: [
      { code: '10100', name: 'Cash', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '10200', name: 'Bank Account', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '10300', name: 'Accounts Receivable', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '10400', name: 'Inventory', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '10501', name: 'GST/HST Input', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '10600', name: 'Prepaid Expenses', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '11100', name: 'Office Equipment', type: 'asset', category: 'fixed_asset', isSystem: true },
      { code: '11200', name: 'Vehicles', type: 'asset', category: 'fixed_asset', isSystem: true },
      { code: '11300', name: 'Accumulated Depreciation', type: 'asset', category: 'contra_asset', isSystem: true },
      { code: '20100', name: 'Accounts Payable', type: 'liability', category: 'current_liability', isSystem: true },
      { code: '20201', name: 'GST/HST Output', type: 'liability', category: 'current_liability', isSystem: true },
      { code: '20300', name: 'CPP Payable', type: 'liability', category: 'current_liability', isSystem: true },
      { code: '20400', name: 'EI Payable', type: 'liability', category: 'current_liability', isSystem: true },
      { code: '21100', name: 'Long-term Debt', type: 'liability', category: 'long_term_liability', isSystem: true },
      { code: '30100', name: "Owner's Equity", type: 'equity', category: 'equity', isSystem: true },
      { code: '30200', name: "Owner's Draw", type: 'equity', category: 'equity', isSystem: true },
      { code: '30300', name: 'Retained Earnings', type: 'equity', category: 'equity', isSystem: true },
      { code: '40100', name: 'Sales Revenue', type: 'revenue', category: 'revenue', isSystem: true },
      { code: '40200', name: 'Sales Returns', type: 'revenue', category: 'contra_revenue', isSystem: true },
      { code: '40300', name: 'Other Income', type: 'revenue', category: 'other_income', isSystem: true },
      { code: '50100', name: 'Cost of Goods Sold', type: 'expense', category: 'cogs', isSystem: true },
      { code: '50200', name: 'Purchases', type: 'expense', category: 'cogs', isSystem: true },
      { code: '60100', name: 'Salaries & Wages', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60200', name: 'Rent Expense', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60300', name: 'Utilities', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60400', name: 'Office Supplies', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60500', name: 'Advertising', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60600', name: 'Insurance', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60700', name: 'Depreciation', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60800', name: 'Professional Fees', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60900', name: 'Bank Charges', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '61000', name: 'Miscellaneous Expense', type: 'expense', category: 'operating_expense', isSystem: true },
    ],
  },

  germany: {
    name: 'Germany',
    currency: 'EUR',
    currencySymbol: '€',
    vatRate: 19,
    fiscalYearStart: '2025-01-01',
    taxYear: 'January to December',
    defaultDateFormat: 'ad',
    tdsRates: {},
    accounts: [
      { code: '10100', name: 'Kasse (Cash)', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '10200', name: 'Bankkonto', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '10300', name: 'Debitoren', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '10400', name: 'Vorräte', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '10501', name: 'Vorsteuer', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '10600', name: 'Aktive Rechnungsabgrenzung', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '11100', name: 'Büroeinrichtung', type: 'asset', category: 'fixed_asset', isSystem: true },
      { code: '11200', name: 'Fahrzeuge', type: 'asset', category: 'fixed_asset', isSystem: true },
      { code: '11300', name: 'Kumulierte Abschreibungen', type: 'asset', category: 'contra_asset', isSystem: true },
      { code: '20100', name: 'Kreditoren', type: 'liability', category: 'current_liability', isSystem: true },
      { code: '20201', name: 'Umsatzsteuer', type: 'liability', category: 'current_liability', isSystem: true },
      { code: '20300', name: 'Lohnsteuer', type: 'liability', category: 'current_liability', isSystem: true },
      { code: '20400', name: 'Sozialversicherung', type: 'liability', category: 'current_liability', isSystem: true },
      { code: '21100', name: 'Langfristige Verbindlichkeiten', type: 'liability', category: 'long_term_liability', isSystem: true },
      { code: '30100', name: 'Kapital', type: 'equity', category: 'equity', isSystem: true },
      { code: '30200', name: 'Privatentnahmen', type: 'equity', category: 'equity', isSystem: true },
      { code: '30300', name: 'Gewinnrücklagen', type: 'equity', category: 'equity', isSystem: true },
      { code: '40100', name: 'Umsatzerlöse', type: 'revenue', category: 'revenue', isSystem: true },
      { code: '40200', name: 'Umsatzerlöse (Skonto)', type: 'revenue', category: 'contra_revenue', isSystem: true },
      { code: '40300', name: 'Sonstige Erträge', type: 'revenue', category: 'other_income', isSystem: true },
      { code: '50100', name: 'Wareneinsatz', type: 'expense', category: 'cogs', isSystem: true },
      { code: '50200', name: 'Einkauf', type: 'expense', category: 'cogs', isSystem: true },
      { code: '60100', name: 'Gehälter', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60200', name: 'Miete', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60300', name: 'Strom & Nebenkosten', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60400', name: 'Telefon & Internet', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60500', name: 'Bürobedarf', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60600', name: 'Werbung', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60700', name: 'Reparaturen', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60800', name: 'Abschreibungen', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60900', name: 'Bankgebühren', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '61000', name: 'Steuerberatung', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '61100', name: 'Sonstige Aufwendungen', type: 'expense', category: 'operating_expense', isSystem: true },
    ],
  },

  france: {
    name: 'France',
    currency: 'EUR',
    currencySymbol: '€',
    vatRate: 20,
    fiscalYearStart: '2025-01-01',
    taxYear: 'January to December',
    defaultDateFormat: 'ad',
    tdsRates: {},
    accounts: [
      { code: '10100', name: 'Caisse', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '10200', name: 'Banque', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '10300', name: 'Clients', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '10400', name: 'Stock de Marchandises', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '10501', name: 'TVA Déductible', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '10600', name: 'Charges Constantes', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '11100', name: 'Mobilier de Bureau', type: 'asset', category: 'fixed_asset', isSystem: true },
      { code: '11200', name: 'Véhicules', type: 'asset', category: 'fixed_asset', isSystem: true },
      { code: '11300', name: 'Amortissements', type: 'asset', category: 'contra_asset', isSystem: true },
      { code: '20100', name: 'Fournisseurs', type: 'liability', category: 'current_liability', isSystem: true },
      { code: '20201', name: 'TVA Collectée', type: 'liability', category: 'current_liability', isSystem: true },
      { code: '20300', name: 'Prélèvement à la Source', type: 'liability', category: 'current_liability', isSystem: true },
      { code: '20400', name: 'Charges Sociales', type: 'liability', category: 'current_liability', isSystem: true },
      { code: '21100', name: 'Emprunts', type: 'liability', category: 'long_term_liability', isSystem: true },
      { code: '30100', name: 'Capital', type: 'equity', category: 'equity', isSystem: true },
      { code: '30200', name: 'Prélèvements', type: 'equity', category: 'equity', isSystem: true },
      { code: '30300', name: 'Réserves', type: 'equity', category: 'equity', isSystem: true },
      { code: '40100', name: 'Ventes de Marchandises', type: 'revenue', category: 'revenue', isSystem: true },
      { code: '40200', name: 'Rabais et Ristournes', type: 'revenue', category: 'contra_revenue', isSystem: true },
      { code: '40300', name: 'Autres Produits', type: 'revenue', category: 'other_income', isSystem: true },
      { code: '50100', name: 'Achats de Marchandises', type: 'expense', category: 'cogs', isSystem: true },
      { code: '50200', name: 'Achats', type: 'expense', category: 'cogs', isSystem: true },
      { code: '60100', name: 'Salaires', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60200', name: 'Loyer', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60300', name: 'Électricité', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60400', name: 'Téléphone & Internet', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60500', name: 'Fournitures de Bureau', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60600', name: 'Publicité', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60700', name: 'Entretien et Réparations', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60800', name: 'Dotations aux Amortissements', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60900', name: 'Frais Bancaires', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '61000', name: 'Honoraires', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '61100', name: 'Charges Diverses', type: 'expense', category: 'operating_expense', isSystem: true },
    ],
  },

  japan: {
    name: 'Japan',
    currency: 'JPY',
    currencySymbol: '¥',
    vatRate: 10,
    fiscalYearStart: '2025-04-01',
    taxYear: 'April to March',
    defaultDateFormat: 'ad',
    tdsRates: {},
    accounts: [
      { code: '10100', name: '現金 (Cash)', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '10200', name: '普通預金 (Bank)', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '10300', name: '売掛金 (Receivables)', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '10400', name: '商品 (Inventory)', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '10501', name: '仮払消費税 (Input VAT)', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '10600', name: '前払費用 (Prepaid)', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '11100', name: '備品 (Equipment)', type: 'asset', category: 'fixed_asset', isSystem: true },
      { code: '11200', name: '車両 (Vehicles)', type: 'asset', category: 'fixed_asset', isSystem: true },
      { code: '11300', name: '減価償却累計額 (Accum Depr)', type: 'asset', category: 'contra_asset', isSystem: true },
      { code: '20100', name: '買掛金 (Payables)', type: 'liability', category: 'current_liability', isSystem: true },
      { code: '20201', name: '仮受消費税 (Output VAT)', type: 'liability', category: 'current_liability', isSystem: true },
      { code: '20300', name: '源泉所得税 (Withholding)', type: 'liability', category: 'current_liability', isSystem: true },
      { code: '20400', name: '社会保険料 (Social Ins)', type: 'liability', category: 'current_liability', isSystem: true },
      { code: '21100', name: '長期借入金 (LT Loans)', type: 'liability', category: 'long_term_liability', isSystem: true },
      { code: '30100', name: '資本金 (Capital)', type: 'equity', category: 'equity', isSystem: true },
      { code: '30200', name: '役員貸付金 (Drawings)', type: 'equity', category: 'equity', isSystem: true },
      { code: '30300', name: '利益剰余金 (Retained)', type: 'equity', category: 'equity', isSystem: true },
      { code: '40100', name: '売上高 (Sales)', type: 'revenue', category: 'revenue', isSystem: true },
      { code: '40200', name: '売上値引 (Returns)', type: 'revenue', category: 'contra_revenue', isSystem: true },
      { code: '40300', name: '雑収入 (Other Income)', type: 'revenue', category: 'other_income', isSystem: true },
      { code: '50100', name: '売上原価 (COGS)', type: 'expense', category: 'cogs', isSystem: true },
      { code: '50200', name: '仕入 (Purchases)', type: 'expense', category: 'cogs', isSystem: true },
      { code: '60100', name: '給料 (Salaries)', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60200', name: '家賃 (Rent)', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60300', name: '水道光熱費 (Utilities)', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60400', name: '通信費 (Communication)', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60500', name: '消耗品費 (Supplies)', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60600', name: '広告宣伝費 (Advertising)', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60700', name: '修繕費 (Repairs)', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60800', name: '減価償却費 (Depreciation)', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60900', name: '支払手数料 (Bank Fees)', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '61000', name: '報酬料 (Professional)', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '61100', name: '雑費 (Miscellaneous)', type: 'expense', category: 'operating_expense', isSystem: true },
    ],
  },

  singapore: {
    name: 'Singapore',
    currency: 'SGD',
    currencySymbol: 'S$',
    vatRate: 9,
    fiscalYearStart: '2025-01-01',
    taxYear: 'January to December',
    defaultDateFormat: 'ad',
    tdsRates: {},
    accounts: [
      { code: '10100', name: 'Cash', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '10200', name: 'Bank Account', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '10300', name: 'Trade Receivables', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '10400', name: 'Inventory', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '10501', name: 'GST Input', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '10600', name: 'Prepaid Expenses', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '11100', name: 'Office Equipment', type: 'asset', category: 'fixed_asset', isSystem: true },
      { code: '11200', name: 'Motor Vehicles', type: 'asset', category: 'fixed_asset', isSystem: true },
      { code: '11300', name: 'Accumulated Depreciation', type: 'asset', category: 'contra_asset', isSystem: true },
      { code: '20100', name: 'Trade Payables', type: 'liability', category: 'current_liability', isSystem: true },
      { code: '20201', name: 'GST Output', type: 'liability', category: 'current_liability', isSystem: true },
      { code: '20300', name: 'CPF Payable', type: 'liability', category: 'current_liability', isSystem: true },
      { code: '20400', name: 'Withholding Tax', type: 'liability', category: 'current_liability', isSystem: true },
      { code: '21100', name: 'Long-term Loans', type: 'liability', category: 'long_term_liability', isSystem: true },
      { code: '30100', name: 'Capital', type: 'equity', category: 'equity', isSystem: true },
      { code: '30200', name: 'Drawings', type: 'equity', category: 'equity', isSystem: true },
      { code: '30300', name: 'Retained Earnings', type: 'equity', category: 'equity', isSystem: true },
      { code: '40100', name: 'Sales Revenue', type: 'revenue', category: 'revenue', isSystem: true },
      { code: '40200', name: 'Sales Returns', type: 'revenue', category: 'contra_revenue', isSystem: true },
      { code: '40300', name: 'Other Income', type: 'revenue', category: 'other_income', isSystem: true },
      { code: '50100', name: 'Cost of Goods Sold', type: 'expense', category: 'cogs', isSystem: true },
      { code: '50200', name: 'Purchases', type: 'expense', category: 'cogs', isSystem: true },
      { code: '60100', name: 'Salaries', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60200', name: 'Rent', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60300', name: 'Utilities', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60400', name: 'Telephone & Internet', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60500', name: 'Office Expenses', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60600', name: 'Marketing', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60700', name: 'Repairs', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60800', name: 'Depreciation', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60900', name: 'Bank Charges', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '61000', name: 'Professional Fees', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '61100', name: 'Miscellaneous', type: 'expense', category: 'operating_expense', isSystem: true },
    ],
  },

  uae: {
    name: 'United Arab Emirates',
    currency: 'AED',
    currencySymbol: 'د.إ',
    vatRate: 5,
    fiscalYearStart: '2025-01-01',
    taxYear: 'January to December',
    defaultDateFormat: 'ad',
    tdsRates: {},
    accounts: [
      { code: '10100', name: 'Cash', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '10200', name: 'Bank Account', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '10300', name: 'Trade Receivables', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '10400', name: 'Inventory', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '10501', name: 'VAT Input', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '10600', name: 'Prepaid Expenses', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '11100', name: 'Office Equipment', type: 'asset', category: 'fixed_asset', isSystem: true },
      { code: '11200', name: 'Vehicles', type: 'asset', category: 'fixed_asset', isSystem: true },
      { code: '11300', name: 'Accumulated Depreciation', type: 'asset', category: 'contra_asset', isSystem: true },
      { code: '20100', name: 'Trade Payables', type: 'liability', category: 'current_liability', isSystem: true },
      { code: '20201', name: 'VAT Output', type: 'liability', category: 'current_liability', isSystem: true },
      { code: '20300', name: 'WPS Payable', type: 'liability', category: 'current_liability', isSystem: true },
      { code: '20400', name: 'End of Service', type: 'liability', category: 'current_liability', isSystem: true },
      { code: '21100', name: 'Long-term Liabilities', type: 'liability', category: 'long_term_liability', isSystem: true },
      { code: '30100', name: 'Capital', type: 'equity', category: 'equity', isSystem: true },
      { code: '30200', name: 'Drawings', type: 'equity', category: 'equity', isSystem: true },
      { code: '30300', name: 'Retained Earnings', type: 'equity', category: 'equity', isSystem: true },
      { code: '40100', name: 'Sales Revenue', type: 'revenue', category: 'revenue', isSystem: true },
      { code: '40200', name: 'Sales Returns', type: 'revenue', category: 'contra_revenue', isSystem: true },
      { code: '40300', name: 'Other Income', type: 'revenue', category: 'other_income', isSystem: true },
      { code: '50100', name: 'Cost of Goods Sold', type: 'expense', category: 'cogs', isSystem: true },
      { code: '50200', name: 'Purchases', type: 'expense', category: 'cogs', isSystem: true },
      { code: '60100', name: 'Salaries', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60200', name: 'Rent', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60300', name: 'Utilities', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60400', name: 'Telephone & Internet', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60500', name: 'Office Expenses', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60600', name: 'Marketing', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60700', name: 'Repairs', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60800', name: 'Depreciation', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60900', name: 'Bank Charges', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '61000', name: 'Professional Fees', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '61100', name: 'Miscellaneous', type: 'expense', category: 'operating_expense', isSystem: true },
    ],
  },

  southafrica: {
    name: 'South Africa',
    currency: 'ZAR',
    currencySymbol: 'R',
    vatRate: 15,
    fiscalYearStart: '2025-03-01',
    taxYear: 'March 1 to February 28',
    defaultDateFormat: 'ad',
    tdsRates: {},
    accounts: [
      { code: '10100', name: 'Petty Cash', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '10200', name: 'Bank', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '10300', name: 'Trade Debtors', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '10400', name: 'Stock', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '10501', name: 'VAT Input', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '10600', name: 'Prepaid Expenses', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '11100', name: 'Office Equipment', type: 'asset', category: 'fixed_asset', isSystem: true },
      { code: '11200', name: 'Vehicles', type: 'asset', category: 'fixed_asset', isSystem: true },
      { code: '11300', name: 'Accumulated Depreciation', type: 'asset', category: 'contra_asset', isSystem: true },
      { code: '20100', name: 'Trade Creditors', type: 'liability', category: 'current_liability', isSystem: true },
      { code: '20201', name: 'VAT Output', type: 'liability', category: 'current_liability', isSystem: true },
      { code: '20300', name: 'PAYE Payable', type: 'liability', category: 'current_liability', isSystem: true },
      { code: '20400', name: 'UIF Payable', type: 'liability', category: 'current_liability', isSystem: true },
      { code: '21100', name: 'Long-term Debt', type: 'liability', category: 'long_term_liability', isSystem: true },
      { code: '30100', name: 'Capital', type: 'equity', category: 'equity', isSystem: true },
      { code: '30200', name: 'Drawings', type: 'equity', category: 'equity', isSystem: true },
      { code: '30300', name: 'Retained Earnings', type: 'equity', category: 'equity', isSystem: true },
      { code: '40100', name: 'Sales', type: 'revenue', category: 'revenue', isSystem: true },
      { code: '40200', name: 'Sales Returns', type: 'revenue', category: 'contra_revenue', isSystem: true },
      { code: '40300', name: 'Other Income', type: 'revenue', category: 'other_income', isSystem: true },
      { code: '50100', name: 'Cost of Sales', type: 'expense', category: 'cogs', isSystem: true },
      { code: '50200', name: 'Purchases', type: 'expense', category: 'cogs', isSystem: true },
      { code: '60100', name: 'Salaries', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60200', name: 'Rent', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60300', name: 'Electricity', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60400', name: 'Telephone & Internet', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60500', name: 'Office Expenses', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60600', name: 'Advertising', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60700', name: 'Repairs', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60800', name: 'Depreciation', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60900', name: 'Bank Charges', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '61000', name: 'Professional Fees', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '61100', name: 'Miscellaneous', type: 'expense', category: 'operating_expense', isSystem: true },
    ],
  },

  newzealand: {
    name: 'New Zealand',
    currency: 'NZD',
    currencySymbol: 'NZ$',
    vatRate: 15,
    fiscalYearStart: '2025-04-01',
    taxYear: 'April 1 to March 31',
    defaultDateFormat: 'ad',
    tdsRates: {},
    accounts: [
      { code: '10100', name: 'Cash', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '10200', name: 'Bank Account', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '10300', name: 'Trade Receivables', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '10400', name: 'Inventory', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '10501', name: 'GST Input', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '10600', name: 'Prepaid Expenses', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '11100', name: 'Office Equipment', type: 'asset', category: 'fixed_asset', isSystem: true },
      { code: '11200', name: 'Vehicles', type: 'asset', category: 'fixed_asset', isSystem: true },
      { code: '11300', name: 'Accumulated Depreciation', type: 'asset', category: 'contra_asset', isSystem: true },
      { code: '20100', name: 'Trade Payables', type: 'liability', category: 'current_liability', isSystem: true },
      { code: '20201', name: 'GST Output', type: 'liability', category: 'current_liability', isSystem: true },
      { code: '20300', name: 'PAYE Payable', type: 'liability', category: 'current_liability', isSystem: true },
      { code: '20400', name: 'KiwiSaver', type: 'liability', category: 'current_liability', isSystem: true },
      { code: '21100', name: 'Long-term Debt', type: 'liability', category: 'long_term_liability', isSystem: true },
      { code: '30100', name: 'Capital', type: 'equity', category: 'equity', isSystem: true },
      { code: '30200', name: 'Drawings', type: 'equity', category: 'equity', isSystem: true },
      { code: '30300', name: 'Retained Earnings', type: 'equity', category: 'equity', isSystem: true },
      { code: '40100', name: 'Sales Revenue', type: 'revenue', category: 'revenue', isSystem: true },
      { code: '40200', name: 'Sales Returns', type: 'revenue', category: 'contra_revenue', isSystem: true },
      { code: '40300', name: 'Other Income', type: 'revenue', category: 'other_income', isSystem: true },
      { code: '50100', name: 'Cost of Goods Sold', type: 'expense', category: 'cogs', isSystem: true },
      { code: '50200', name: 'Purchases', type: 'expense', category: 'cogs', isSystem: true },
      { code: '60100', name: 'Salaries', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60200', name: 'Rent', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60300', name: 'Utilities', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60400', name: 'Telephone & Internet', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60500', name: 'Office Expenses', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60600', name: 'Marketing', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60700', name: 'Repairs', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60800', name: 'Depreciation', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60900', name: 'Bank Fees', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '61000', name: 'Accounting Fees', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '61100', name: 'Miscellaneous', type: 'expense', category: 'operating_expense', isSystem: true },
    ],
  },

  ireland: {
    name: 'Ireland',
    currency: 'EUR',
    currencySymbol: '€',
    vatRate: 23,
    fiscalYearStart: '2025-01-01',
    taxYear: 'January to December',
    defaultDateFormat: 'ad',
    tdsRates: {},
    accounts: [
      { code: '10100', name: 'Cash', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '10200', name: 'Bank', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '10300', name: 'Debtors', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '10400', name: 'Stock', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '10501', name: 'VAT Input', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '10600', name: 'Prepayments', type: 'asset', category: 'current_asset', isSystem: true },
      { code: '11100', name: 'Office Equipment', type: 'asset', category: 'fixed_asset', isSystem: true },
      { code: '11200', name: 'Vehicles', type: 'asset', category: 'fixed_asset', isSystem: true },
      { code: '11300', name: 'Accumulated Depreciation', type: 'asset', category: 'contra_asset', isSystem: true },
      { code: '20100', name: 'Creditors', type: 'liability', category: 'current_liability', isSystem: true },
      { code: '20201', name: 'VAT Output', type: 'liability', category: 'current_liability', isSystem: true },
      { code: '20300', name: 'PAYE/PRSI', type: 'liability', category: 'current_liability', isSystem: true },
      { code: '20400', name: 'UCD Liabilities', type: 'liability', category: 'current_liability', isSystem: true },
      { code: '21100', name: 'Loans', type: 'liability', category: 'long_term_liability', isSystem: true },
      { code: '30100', name: 'Capital', type: 'equity', category: 'equity', isSystem: true },
      { code: '30200', name: 'Drawings', type: 'equity', category: 'equity', isSystem: true },
      { code: '30300', name: 'Retained Earnings', type: 'equity', category: 'equity', isSystem: true },
      { code: '40100', name: 'Turnover', type: 'revenue', category: 'revenue', isSystem: true },
      { code: '40200', name: 'Sales Returns', type: 'revenue', category: 'contra_revenue', isSystem: true },
      { code: '40300', name: 'Other Income', type: 'revenue', category: 'other_income', isSystem: true },
      { code: '50100', name: 'Cost of Sales', type: 'expense', category: 'cogs', isSystem: true },
      { code: '50200', name: 'Purchases', type: 'expense', category: 'cogs', isSystem: true },
      { code: '60100', name: 'Salaries', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60200', name: 'Rent', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60300', name: 'Utilities', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60400', name: 'Telephone', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60500', name: 'Office Expenses', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60600', name: 'Advertising', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60700', name: 'Repairs', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60800', name: 'Depreciation', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '60900', name: 'Bank Charges', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '61000', name: 'Professional Fees', type: 'expense', category: 'operating_expense', isSystem: true },
      { code: '61100', name: 'Sundry Expenses', type: 'expense', category: 'operating_expense', isSystem: true },
    ],
  },
};

function getChartOfAccounts(countryCode) {
  return chartOfAccounts[countryCode] || chartOfAccounts['nepal'];
}

function getSupportedCountries() {
  return Object.keys(chartOfAccounts).map(key => ({
    code: key,
    name: chartOfAccounts[key].name,
    currency: chartOfAccounts[key].currency,
    currencySymbol: chartOfAccounts[key].currencySymbol,
    vatRate: chartOfAccounts[key].vatRate,
    taxYear: chartOfAccounts[key].taxYear,
  }));
}

function getCountryRules(countryCode) {
  const country = chartOfAccounts[countryCode];
  if (!country) return null;
  return {
    name: country.name,
    currency: country.currency,
    currencySymbol: country.currencySymbol,
    vatRate: country.vatRate,
    salesTaxRate: country.salesTaxRate || 0,
    taxYear: country.taxYear,
    tdsRates: country.tdsRates || {},
    fiscalYearStart: country.fiscalYearStart,
    defaultDateFormat: country.defaultDateFormat,
  };
}

module.exports = { getChartOfAccounts, getSupportedCountries, getCountryRules, chartOfAccounts };
